In [1]:
!pip install -q \
transformers==4.51.3 \
datasets==3.6.0 \
accelerate==1.7.0 \
sentencepiece \
evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 104.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 44.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.1/362.1 kB 34.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 48.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 94.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.19.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [2]:
import pandas as pd

# Read and display sample_submission.csv
sample_submission_df = pd.read_csv('/content/sample_submission.csv')
# Read and display /content/test.csv
test_df = pd.read_csv('/content/test.csv')
# Read and display /content/train.csv
train_df = pd.read_csv('/content/train.csv')

In [3]:
print(sample_submission_df.dtypes)

ID             int64
Prediction    object
dtype: object

In [4]:
print(train_df.dtypes)

id         int64
prompt    object
A         object
B         object
C         object
D         object
E         object
answer    object
dtype: object

In [5]:
print(test_df.dtypes)

id         int64
prompt    object
A         object
B         object
C         object
D         object
E         object
dtype: object

In [6]:
sample_submission_df.head()

   ID Prediction
0   1      A B C
1   2      A B C
2   3      A B C
3   4      A B C
4   5      A B C

In [7]:
test_df.head()

,id,prompt,A,B,C,D,E
0,1,Pick the best possible answer: What is the rel...,"For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p..."
1,2,"What is the estimated redshift of CEERS-93316,...","Approximately z = 6.0, corresponding to 1 bill...","Approximately z = 16.7, corresponding to 235.8...","Approximately z = 3.0, corresponding to 5 bill...","Approximately z = 10.0, corresponding to 13 bi...","Approximately z = 13.0, corresponding to 30 bi..."
2,3,Pick the best possible answer: What is the rea...,The sun appears yellowish due to a reflection ...,"The longer wavelengths of light, such as red a...",The sun appears yellowish due to the scatterin...,The sun emits a yellow light due to its own sp...,The atmosphere absorbs the shorter wavelengths...
3,4,What is the significance of the redshift-dista...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...
4,5,What is the Landau-Lifshitz-Gilbert equation u...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...

In [8]:
train_df.head()

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

In [9]:
import torch
import transformers
import datasets
import accelerate
import transformers

import os
import gc
import math
import random
import warnings
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from tqdm.auto import tqdm

from sklearn.model_selection import train_test_split

from transformers import (
    AutoTokenizer,
    AutoModelForMultipleChoice,
    get_cosine_schedule_with_warmup
)

from torch.utils.data import Dataset, DataLoader

# **MODEL: microsoft/deberta-v3-base**

In [10]:
# MODEL: microsoft/deberta-v3-base STARTS HERE

In [11]:

# STEP 1
# Setup + Configuration + Data Loading
# Google Colab | Tesla T4 | PyTorch 2.11


import os
import gc
import math
import random
import warnings

import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from tqdm.auto import tqdm

from sklearn.model_selection import train_test_split

from transformers import (
    AutoTokenizer,
    AutoModelForMultipleChoice,
    get_cosine_schedule_with_warmup
)

from torch.utils.data import Dataset, DataLoader

warnings.filterwarnings("ignore")


# Reproducibility


SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)


# Device


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("=" * 60)
print("Torch          :", torch.__version__)
print("CUDA           :", torch.version.cuda)

import transformers

print("Transformers   :", transformers.__version__)

if torch.cuda.is_available():

    print("GPU            :", torch.cuda.get_device_name(0))

    print(
        "GPU Memory     : %.2f GB"
        % (
            torch.cuda.get_device_properties(0).total_memory
            / 1024**3
        )
    )

print("=" * 60)


# Performance


torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.backends.cudnn.benchmark = True

torch.set_float32_matmul_precision("high")


# Configuration


MODEL_NAME = "microsoft/deberta-v3-base"

MAX_LENGTH = 320

TRAIN_BATCH_SIZE = 1

VALID_BATCH_SIZE = 2

GRAD_ACCUM = 16

EPOCHS = 4

LR = 2e-5

WEIGHT_DECAY = 0.01

WARMUP_RATIO = 0.10

BEST_MODEL_PATH = "best_model.pt"

print("\nModel :", MODEL_NAME)


# Tokenizer


tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

print("Tokenizer Loaded")


# File Paths


TRAIN_PATH = "/content/train.csv"
TEST_PATH = "/content/test.csv"
SAMPLE_PATH = "/content/sample_submission.csv"


# Load Data


train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)
sample_submission_df = pd.read_csv(SAMPLE_PATH)

print()

print("Train Shape :", train_df.shape)
print("Test Shape  :", test_df.shape)

display(train_df.head())


# Fill Missing


TEXT_COLUMNS = [
    "prompt",
    "A",
    "B",
    "C",
    "D",
    "E"
]

for col in TEXT_COLUMNS:

    train_df[col] = (
        train_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    test_df[col] = (
        test_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
    )


# Labels


LABEL2ID = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

ID2LABEL = {v: k for k, v in LABEL2ID.items()}

train_df["label"] = train_df["answer"].map(LABEL2ID)

print()

print(train_df["label"].value_counts().sort_index())

# Shuffle

train_df = train_df.sample(
    frac=1,
    random_state=SEED
).reset_index(drop=True)

# Train / Validation Split

train_data, valid_data = train_test_split(

    train_df,

    test_size=0.10,

    random_state=SEED,

    stratify=train_df["label"]

)

train_data = train_data.reset_index(drop=True)
valid_data = valid_data.reset_index(drop=True)

print()

print("Training Samples  :", len(train_data))
print("Validation Samples:", len(valid_data))
print("Test Samples      :", len(test_df))

# Cleanup

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("\n STEP 1 Complete.")

============================================================
Torch          : 2.11.0+cu128
CUDA           : 12.8
Transformers   : 4.51.3
GPU            : Tesla T4
GPU Memory     : 14.56 GB
============================================================

Model : microsoft/deberta-v3-base

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

Tokenizer Loaded

Train Shape : (2000, 8)
Test Shape  : (500, 7)

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

label
0    369
1    490
2    459
3    358
4    324
Name: count, dtype: int64

Training Samples  : 1800
Validation Samples: 200
Test Samples      : 500

Chunk 1 Complete.

In [12]:

# STEP 2
# Fast Dataset (Pre-tokenized)


from torch.utils.data import Dataset, DataLoader
import os

# Dataset

class MCQDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_length=320, train=True):

        self.train = train
        self.samples = []

        print("Tokenizing dataset...")

        for _, row in tqdm(
            dataframe.iterrows(),
            total=len(dataframe)
        ):

            prompt = str(row["prompt"])

            choices = [
                str(row["A"]),
                str(row["B"]),
                str(row["C"]),
                str(row["D"]),
                str(row["E"])
            ]

            encoding = tokenizer(

                [prompt] * 5,

                choices,

                truncation=True,

                max_length=max_length,

                padding=False,

                return_attention_mask=True

            )

            sample = {

                "input_ids": encoding["input_ids"],

                "attention_mask": encoding["attention_mask"]

            }

            if "token_type_ids" in encoding:

                sample["token_type_ids"] = encoding["token_type_ids"]

            if train:

                sample["labels"] = int(row["label"])

            self.samples.append(sample)

        print("Finished Tokenizing.")

    def __len__(self):

        return len(self.samples)

    def __getitem__(self, idx):

        return self.samples[idx]


# Dynamic Padding

def collate_fn(features):

    labels = None

    if "labels" in features[0]:

        labels = torch.tensor(
            [x["labels"] for x in features],
            dtype=torch.long
        )

    batch_size = len(features)

    num_choices = len(features[0]["input_ids"])

    flattened = []

    for feature in features:

        for i in range(num_choices):

            item = {

                "input_ids":
                    feature["input_ids"][i],

                "attention_mask":
                    feature["attention_mask"][i]

            }

            if "token_type_ids" in feature:

                item["token_type_ids"] = (
                    feature["token_type_ids"][i]
                )

            flattened.append(item)

    batch = tokenizer.pad(

        flattened,

        padding="longest",

        pad_to_multiple_of=8,

        return_tensors="pt"

    )

    batch = {

        k: v.view(batch_size, num_choices, -1)

        for k, v in batch.items()

    }

    if labels is not None:

        batch["labels"] = labels

    return batch


# Build datasets

train_dataset = MCQDataset(

    train_data,

    tokenizer,

    MAX_LENGTH,

    train=True

)

valid_dataset = MCQDataset(

    valid_data,

    tokenizer,

    MAX_LENGTH,

    train=True

)

test_dataset = MCQDataset(

    test_df,

    tokenizer,

    MAX_LENGTH,

    train=False

)

print()

print("Train :", len(train_dataset))
print("Valid :", len(valid_dataset))
print("Test  :", len(test_dataset))

# DataLoader

NUM_WORKERS = min(4, os.cpu_count())

train_loader = DataLoader(

    train_dataset,

    batch_size=TRAIN_BATCH_SIZE,

    shuffle=True,

    collate_fn=collate_fn,

    pin_memory=True,

    num_workers=NUM_WORKERS,

    persistent_workers=(NUM_WORKERS > 0),

    prefetch_factor=2 if NUM_WORKERS > 0 else None,

    drop_last=True

)

valid_loader = DataLoader(

    valid_dataset,

    batch_size=VALID_BATCH_SIZE,

    shuffle=False,

    collate_fn=collate_fn,

    pin_memory=True,

    num_workers=NUM_WORKERS,

    persistent_workers=(NUM_WORKERS > 0),

    prefetch_factor=2 if NUM_WORKERS > 0 else None,

    drop_last=False

)

test_loader = DataLoader(

    test_dataset,

    batch_size=VALID_BATCH_SIZE,

    shuffle=False,

    collate_fn=collate_fn,

    pin_memory=True,

    num_workers=NUM_WORKERS,

    persistent_workers=(NUM_WORKERS > 0),

    prefetch_factor=2 if NUM_WORKERS > 0 else None,

    drop_last=False

)

print("\nDataLoaders Ready")

# Test batch

batch = next(iter(train_loader))

print("\nBatch Shapes")

for k, v in batch.items():

    print(f"{k:18} {tuple(v.shape)}")

gc.collect()

if torch.cuda.is_available():

    torch.cuda.empty_cache()

print("\nSTEP 2 Complete")

Tokenizing dataset...

  0%|          | 0/1800 [00:00<?, ?it/s]

Finished Tokenizing.
Tokenizing dataset...

  0%|          | 0/200 [00:00<?, ?it/s]

Finished Tokenizing.
Tokenizing dataset...

  0%|          | 0/500 [00:00<?, ?it/s]

Finished Tokenizing.

Train : 1800
Valid : 200
Test  : 500

DataLoaders Ready

You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

Batch Shapes
input_ids          (1, 5, 80)
attention_mask     (1, 5, 80)
token_type_ids     (1, 5, 80)
labels             (1,)

Chunk 2 Complete

In [13]:

# STEP 3
# Model + Optimizer + Scheduler + AMP + Validation (Debug)
# Compatible with Chunk 1 & Chunk 2


import gc
import numpy as np
import torch
import transformers

print("=" * 60)
print("Loading Model")
print("=" * 60)

print("Torch Version        :", torch.__version__)
print("Transformers Version :", transformers.__version__)
print("Default Dtype        :", torch.get_default_dtype())
print("Device               :", DEVICE)

# Load Model

model = AutoModelForMultipleChoice.from_pretrained(
    MODEL_NAME,
    ignore_mismatched_sizes=True
)

print("\nAfter from_pretrained()")
print(next(model.parameters()).dtype)

# Force FP32

model.float()

print("\nAfter model.float()")
print(next(model.parameters()).dtype)

# Gradient Checkpointing

model.gradient_checkpointing_enable()
model.config.use_cache = False

# Move to GPU

model.to(DEVICE)

print("\nAfter model.to()")
print(next(model.parameters()).dtype)

# Count parameter dtypes

fp16_params = 0
fp32_params = 0

for p in model.parameters():

    if p.dtype == torch.float16:
        fp16_params += 1

    elif p.dtype == torch.float32:
        fp32_params += 1

print("\nParameter Summary")
print("----------------------------")
print("FP16 Parameters :", fp16_params)
print("FP32 Parameters :", fp32_params)

# STOP IMMEDIATELY IF MODEL IS FP16

if fp16_params > 0:

    raise RuntimeError(
        "ERROR: Model parameters are FP16 before training.\n"
        "AMP requires FP32 model weights.\n"
        "Do NOT continue until this is fixed."
    )

print("\nModel verified as FP32.")

# Parameter Count

total_params = sum(
    p.numel()
    for p in model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print("\nTotal Parameters :", f"{total_params:,}")
print("Trainable Params :", f"{trainable_params:,}")

# Optimizer

no_decay = ["bias", "LayerNorm.weight"]

optimizer_grouped_parameters = [

    {
        "params":[
            p for n,p in model.named_parameters()
            if not any(nd in n for nd in no_decay)
        ],
        "weight_decay":WEIGHT_DECAY
    },

    {
        "params":[
            p for n,p in model.named_parameters()
            if any(nd in n for nd in no_decay)
        ],
        "weight_decay":0.0
    }

]

optimizer = torch.optim.AdamW(

    optimizer_grouped_parameters,

    lr=LR,

    betas=(0.9,0.999),

    eps=1e-8

)

print("\nOptimizer Ready")

# Scheduler

steps_per_epoch = len(train_loader)

optimizer_steps_per_epoch = (
    steps_per_epoch + GRAD_ACCUM - 1
) // GRAD_ACCUM

total_training_steps = optimizer_steps_per_epoch * EPOCHS

warmup_steps = int(
    total_training_steps * WARMUP_RATIO
)

scheduler = get_cosine_schedule_with_warmup(

    optimizer,

    num_warmup_steps=warmup_steps,

    num_training_steps=total_training_steps

)

print("Scheduler Ready")
print("Total Steps :", total_training_steps)
print("Warmup Steps:", warmup_steps)

# AMP

scaler = torch.amp.GradScaler("cuda")

print("\nGradScaler Enabled :", scaler.is_enabled())

# mAP@3

def map3(logits, labels):

    top3 = np.argsort(-logits, axis=1)[:, :3]

    score = 0.0

    for truth, pred in zip(labels, top3):

        if truth in pred:

            rank = np.where(pred == truth)[0][0] + 1

            score += 1.0 / rank

    return score / len(labels)

# Validation

@torch.no_grad()
def validate():

    model.eval()

    losses = []
    preds = []
    labels = []

    for batch in valid_loader:

        batch = {
            k: v.to(DEVICE, non_blocking=True)
            for k, v in batch.items()
        }

        with torch.amp.autocast("cuda"):

            outputs = model(**batch)

        losses.append(outputs.loss.item())

        preds.append(
            outputs.logits.float().cpu().numpy()
        )

        labels.append(
            batch["labels"].cpu().numpy()
        )

    preds = np.concatenate(preds)
    labels = np.concatenate(labels)

    acc = (
        preds.argmax(1) == labels
    ).mean()

    score = map3(preds, labels)

    return (
        float(np.mean(losses)),
        float(acc),
        float(score)
    )

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("\nSTEP 3 Complete.")

============================================================
Loading Model
============================================================
Torch Version        : 2.11.0+cu128
Transformers Version : 4.51.3
Default Dtype        : torch.float32
Device               : cuda

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

Some weights of DebertaV2ForMultipleChoice were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

After from_pretrained()
torch.float32

After model.float()
torch.float32

After model.to()
torch.float32

Parameter Summary
----------------------------
FP16 Parameters : 0
FP32 Parameters : 202

Model verified as FP32.

Total Parameters : 184,422,913
Trainable Params : 184,422,913

Optimizer Ready
Scheduler Ready
Total Steps : 452
Warmup Steps: 45

GradScaler Enabled : True

Chunk 3 Complete.

In [14]:

# STEP 4
# Training Loop


import time

best_map3 = -1.0

history = {
    "train_loss": [],
    "valid_loss": [],
    "valid_acc": [],
    "valid_map3": []
}

print("=" * 70)
print("Starting Training")
print("=" * 70)

for epoch in range(EPOCHS):

    print()
    print("=" * 70)
    print(f"Epoch {epoch + 1}/{EPOCHS}")
    print("=" * 70)

    model.train()

    running_loss = 0.0

    optimizer.zero_grad(set_to_none=True)

    progress = tqdm(
        enumerate(train_loader),
        total=len(train_loader),
        leave=True
    )

    start_time = time.time()

    for step, batch in progress:

        batch = {
            k: v.to(DEVICE, non_blocking=True)
            for k, v in batch.items()
        }

        with torch.amp.autocast("cuda"):

            outputs = model(**batch)

            loss = outputs.loss

            loss = loss / GRAD_ACCUM

        scaler.scale(loss).backward()

        running_loss += loss.item() * GRAD_ACCUM

        if (
            (step + 1) % GRAD_ACCUM == 0
            or
            (step + 1) == len(train_loader)
        ):

            scaler.unscale_(optimizer)

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                1.0
            )

            scaler.step(optimizer)

            scaler.update()

            scheduler.step()

            optimizer.zero_grad(set_to_none=True)

        progress.set_postfix(
            loss=f"{running_loss/(step+1):.4f}",
            lr=f"{scheduler.get_last_lr()[0]:.2e}"
        )

    epoch_time = time.time() - start_time

    train_loss = running_loss / len(train_loader)

    valid_loss, valid_acc, valid_map3 = validate()

    history["train_loss"].append(train_loss)
    history["valid_loss"].append(valid_loss)
    history["valid_acc"].append(valid_acc)
    history["valid_map3"].append(valid_map3)

    print()

    print(f"Epoch Time      : {epoch_time:.1f} sec")
    print(f"Train Loss      : {train_loss:.4f}")
    print(f"Validation Loss : {valid_loss:.4f}")
    print(f"Validation Acc  : {valid_acc:.4f}")
    print(f"Validation mAP3 : {valid_map3:.4f}")

    if valid_map3 > best_map3:

        best_map3 = valid_map3

        torch.save(
            model.state_dict(),
            BEST_MODEL_PATH
        )

        print("Best model saved.")

print()
print("=" * 70)
print("Training Finished")
print("=" * 70)

print(f"Best Validation mAP@3 : {best_map3:.5f}")

======================================================================
Starting Training
======================================================================

======================================================================
Epoch 1/4
======================================================================

  0%|          | 0/1800 [00:00<?, ?it/s]

You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

Epoch Time      : 242.7 sec
Train Loss      : 1.4719
Validation Loss : 0.8934
Validation Acc  : 0.7950
Validation mAP3 : 0.8867
Best model saved.

======================================================================
Epoch 2/4
======================================================================

  0%|          | 0/1800 [00:00<?, ?it/s]

Epoch Time      : 242.1 sec
Train Loss      : 0.5978
Validation Loss : 0.1826
Validation Acc  : 0.9800
Validation mAP3 : 0.9875
Best model saved.

======================================================================
Epoch 3/4
======================================================================

  0%|          | 0/1800 [00:00<?, ?it/s]

Epoch Time      : 239.3 sec
Train Loss      : 0.1648
Validation Loss : 0.0767
Validation Acc  : 0.9900
Validation mAP3 : 0.9950
Best model saved.

======================================================================
Epoch 4/4
======================================================================

  0%|          | 0/1800 [00:00<?, ?it/s]

Epoch Time      : 239.1 sec
Train Loss      : 0.0973
Validation Loss : 0.0652
Validation Acc  : 0.9950
Validation mAP3 : 0.9975
Best model saved.

======================================================================
Training Finished
======================================================================
Best Validation mAP@3 : 0.99750

In [15]:

# STEP 5
# Inference + submission.csv


import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm

# Load best model

model.load_state_dict(
    torch.load(BEST_MODEL_PATH, map_location=DEVICE)
)

model.to(DEVICE)
model.eval()

print("Best model loaded.")

# Prediction

all_predictions = []

with torch.no_grad():

    for batch in tqdm(test_loader):

        batch = {
            k: v.to(DEVICE)
            for k, v in batch.items()
        }

        with torch.amp.autocast("cuda"):

            logits = model(**batch).logits

        all_predictions.append(
            logits.float().cpu().numpy()
        )

all_predictions = np.concatenate(all_predictions)

print(all_predictions.shape)

# Top-3

top3 = np.argsort(-all_predictions, axis=1)[:, :3]

predictions = []

for row in top3:

    predictions.append(
        " ".join(
            ID2LABEL[i]
            for i in row
        )
    )

# Submission

submission = sample_submission_df.copy()

submission["Prediction"] = predictions

submission.to_csv(
    "submission.csv",
    index=False
)

print("\nsubmission.csv created.")

display(submission.head())

Best model loaded.

You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

  0%|          | 0/250 [00:00<?, ?it/s]

(500, 5)

submission.csv created.

   ID Prediction
0   1      A B D
1   2      B C D
2   3      B D E
3   4      E C D
4   5      C D A

In [16]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
print(torch.__version__)
print(torch.version.cuda)
print(type(scaler))
print(scaler.is_enabled())

True
Tesla T4
2.11.0+cu128
12.8
<class 'torch.amp.grad_scaler.GradScaler'>
True

In [17]:
import torch
print(torch.__version__)

2.11.0+cu128

# **MODEL: google/electra-base-discriminator**

In [18]:
# MODEL: google/electra-base-discriminator STARTS HERE

In [19]:
# Step 1. Install libraries (Kaggle/Colab)
!pip install -q transformers datasets accelerate evaluate sentencepiece

# Step 2 — Import Libraries
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import torch

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForMultipleChoice,
    TrainingArguments,
    Trainer
)

from sklearn.model_selection import train_test_split

# Step 3 — Load Dataset

train_df = pd.read_csv("/content/train.csv")
test_df = pd.read_csv("/content/test.csv")
sample_submission = pd.read_csv("/content/sample_submission.csv")

print(train_df.shape)
print(test_df.shape)

# Step 4 — Look at the Dataset

train_df.head()

# Step 5 — Convert Answers to Numbers

label2id = {
    "A":0,
    "B":1,
    "C":2,
    "D":3,
    "E":4
}

id2label = {v:k for k,v in label2id.items()}

train_df["label"] = train_df["answer"].map(label2id)

train_df[["answer","label"]].head()

# Step 6 — Train Validation Split
train_df, valid_df = train_test_split(
    train_df,
    test_size=0.1,
    random_state=42,
    stratify=train_df["label"]
)
print(train_df.shape)
print(valid_df.shape)

# Step 7 — Convert to HuggingFace Dataset
train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(valid_df)
test_dataset = Dataset.from_pandas(test_df)

# Step 8 — Download ELECTRA Base
MODEL_NAME = "google/electra-base-discriminator"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Step 9 — Multiple Choice Preprocessing
def preprocess_function(example):

    first_sentences = [example["prompt"]] * 5

    second_sentences = [
        example["A"],
        example["B"],
        example["C"],
        example["D"],
        example["E"]
    ]

    tokenized = tokenizer(
        first_sentences,
        second_sentences,
        truncation=True,
        max_length=384
    )

    tokenized["label"] = example["label"]

    return tokenized

print(train_dataset.column_names)

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df, preserve_index=False)
valid_dataset = Dataset.from_pandas(valid_df, preserve_index=False)
test_dataset = Dataset.from_pandas(test_df, preserve_index=False)

print(train_dataset.column_names)

(2000, 8)
(500, 7)
(1800, 9)
(200, 9)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer', 'label', '__index_level_0__']
['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer', 'label']

In [20]:
# Step 10 — Preprocess Training Data
train_dataset = train_dataset.map(preprocess_function)

# Step 11 — Validation Data
valid_dataset = valid_dataset.map(preprocess_function)

# Step 12 — Test Data
def preprocess_test(example):

    first_sentences = [example["prompt"]] * 5

    second_sentences = [
        example["A"],
        example["B"],
        example["C"],
        example["D"],
        example["E"]
    ]

    return tokenizer(
        first_sentences,
        second_sentences,
        truncation=True,
        max_length=384
    )

test_dataset = test_dataset.map(preprocess_test)

# Step 13 — Verify Everything Worked
print(train_dataset[0].keys())

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

dict_keys(['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer', 'label', 'input_ids', 'token_type_ids', 'attention_mask'])

In [21]:
# PART 2 – Fine-Tuning ELECTRA Base

In [22]:
# Step 14 Remove unwanted columns safely

train_remove = [
    col for col in [
        "id", "prompt", "A", "B", "C", "D", "E",
        "answer", "__index_level_0__"
    ]
    if col in train_dataset.column_names
]

valid_remove = [
    col for col in [
        "id", "prompt", "A", "B", "C", "D", "E",
        "answer", "__index_level_0__"
    ]
    if col in valid_dataset.column_names
]

test_remove = [
    col for col in [
        "id", "prompt", "A", "B", "C", "D", "E",
        "__index_level_0__"
    ]
    if col in test_dataset.column_names
]

train_dataset = train_dataset.remove_columns(train_remove)
valid_dataset = valid_dataset.remove_columns(valid_remove)
test_dataset = test_dataset.remove_columns(test_remove)

print(train_dataset.column_names)
print(valid_dataset.column_names)
print(test_dataset.column_names)


# Step 15 - Check the processed dataset
print(train_dataset[0])

# Step 16 - Load ELECTRA Base
MODEL_NAME = "google/electra-base-discriminator"

model = AutoModelForMultipleChoice.from_pretrained(MODEL_NAME)

# Step 17 - Create Data Collator
from dataclasses import dataclass
from typing import Optional, Union
import torch

from transformers import PreTrainedTokenizerBase
from transformers.tokenization_utils_base import PaddingStrategy

@dataclass
class DataCollatorForMultipleChoice:
    tokenizer: PreTrainedTokenizerBase
    padding: Union[bool, str, PaddingStrategy] = True
    max_length: Optional[int] = None

    def __call__(self, features):

        labels = None
        if "label" in features[0]:
            labels = [feature.pop("label") for feature in features]

        batch_size = len(features)
        num_choices = len(features[0]["input_ids"])

        flattened_features = []

        for feature in features:
            for i in range(num_choices):
                flattened_features.append(
                    {k: v[i] for k, v in feature.items()}
                )

        batch = self.tokenizer.pad(
            flattened_features,
            padding=self.padding,
            max_length=self.max_length,
            return_tensors="pt"
        )

        batch = {
            k: v.view(batch_size, num_choices, -1)
            for k, v in batch.items()
        }

        if labels is not None:
            batch["labels"] = torch.tensor(labels)

        return batch


# Step 18 - Initialize Data Collator
data_collator = DataCollatorForMultipleChoice(tokenizer)

# Step 19 - Training Arguments
training_args = TrainingArguments(
    output_dir="./electra_model",

    learning_rate=1e-5,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    gradient_accumulation_steps=2,

    num_train_epochs=5,

    warmup_ratio=0.1,

    weight_decay=0.05,

    logging_steps=50,

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="eval_loss",

    greater_is_better=False,

    report_to="none",

    fp16=torch.cuda.is_available()
)


# Step 20 - Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    data_collator=data_collator
)

['label', 'input_ids', 'token_type_ids', 'attention_mask']
['label', 'input_ids', 'token_type_ids', 'attention_mask']
['input_ids', 'token_type_ids', 'attention_mask']
{'label': 4, 'input_ids': [[101, 2054, 2003, 1996, 7882, 2828, 1997, 2522, 5886, 10127, 2005, 1996, 2402, 1005, 1055, 3313, 1011, 18036, 6970, 7512, 18721, 1029, 102, 16476, 102], [101, 2054, 2003, 1996, 7882, 2828, 1997, 2522, 5886, 10127, 2005, 1996, 2402, 1005, 1055, 3313, 1011, 18036, 6970, 7512, 18721, 1029, 102, 2522, 5886, 10127, 2051, 102], [101, 2054, 2003, 1996, 7882, 2828, 1997, 2522, 5886, 10127, 2005, 1996, 2402, 1005, 1055, 3313, 1011, 18036, 6970, 7512, 18721, 1029, 102, 13589, 2522, 5886, 10127, 102], [101, 2054, 2003, 1996, 7882, 2828, 1997, 2522, 5886, 10127, 2005, 1996, 2402, 1005, 1055, 3313, 1011, 18036, 6970, 7512, 18721, 1029, 102, 2522, 5886, 10127, 3091, 102], [101, 2054, 2003, 1996, 7882, 2828, 1997, 2522, 5886, 10127, 2005, 1996, 2402, 1005, 1055, 3313, 1011, 18036, 6970, 7512, 18721, 1029, 102, 6705, 1997, 1996, 2522, 5886, 10127, 2181, 1006, 9353, 1007, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of ElectraForMultipleChoice were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.bias', 'classifier.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [23]:
# Step 21 - Train
trainer.train()

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

TrainOutput(global_step=560, training_loss=0.8367738842964172, metrics={'train_runtime': 581.7035, 'train_samples_per_second': 15.472, 'train_steps_per_second': 0.963, 'total_flos': 2436900381271920.0, 'train_loss': 0.8367738842964172, 'epoch': 4.96})

In [24]:
# Step 22 - Evaluate on the Validation Set
eval_results = trainer.evaluate()

print(eval_results)

# Step 23 - Predict on the Test Set
test_predictions = trainer.predict(test_dataset)

# Step 24 - Check prediction shape
logits = test_predictions.predictions

print(logits.shape)

# Step 25 - Get the predicted answer (Top-1)
pred_ids = np.argmax(logits, axis=1)

id2label = {
    0: "A",
    1: "B",
    2: "C",
    3: "D",
    4: "E"
}

pred_answers = [id2label[i] for i in pred_ids]


# Step 26 - Create submission
submission = pd.DataFrame({
    "ID": test_df["id"],
    "Prediction": pred_answers
})

submission.head()


# Step 27 - Save submission
submission.to_csv("ELECTRA submission.csv", index=False)

print("ELECTRA submission.csv created successfully!")

{'eval_loss': 0.260030597448349, 'eval_runtime': 1.8749, 'eval_samples_per_second': 106.67, 'eval_steps_per_second': 13.334, 'epoch': 4.96}
(500, 5)
ELECTRA submission.csv created successfully!